<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ASDP1547PO01976" name="com.qainfotech.tap.training.snl.api.BoardTest" tests="11" failures="0" timestamp="27 Jul 2017 13:08:29 GMT" time="0.182" errors="1">
  <testcase name="registerPlayerTest" time="0.010" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="NoUserWithSuchUUIDExceptionTest" time="0.032" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="rollDiceTestForNotChangingThePosition" time="0.006" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="registerPlayerTestForPlayerExistException" time="0.009" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="rollDiceForInvalidTurnException" time="0.007" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="rollDiceForLadder" time="0.015" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="rollDiceForSnake" time="0.007" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="registerPlayerTestForGameInProgressException" time="0.013" classname="com.qainfotech.tap.training.snl.api.BoardTest">
    <error type="org.testng.TestException" message="
Method BoardTest.registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67] should have thrown an exception of type class com.qainfotech.tap.training.snl.api.GameInProgressException">
      <![CDATA[org.testng.TestException: 
Method BoardTest.registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67] should have thrown an exception of type class com.qainfotech.tap.training.snl.api.GameInProgressException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- registerPlayerTestForGameInProgressException -->
  <testcase name="deletePlayerTest" time="0.062" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="registerPlayerTestForMaxPlayerException" time="0.012" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
  <testcase name="rollDiceTestForStartingTheGame" time="0.009" classname="com.qainfotech.tap.training.snl.api.BoardTest"/>
</testsuite> <!-- com.qainfotech.tap.training.snl.api.BoardTest -->
